[project]
name = "projet-scrap-devoir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "marimo>=0.18.4",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
